### ISSUE TITLE
Blog V2 - Weak typing caused most of our runtime errors in V1.

### ISSUE THREAD

**Issue by StarpTech** [Staffjoy/v2#1]
Hi,
in the [blog ](https://blog.staffjoy.com/staffjoys-v2-architecture-9d2fcb4015fd#.ogyixsrrw) you saying

> Weak typing caused most of our runtime errors in V1. To address this, we decided to use strong typing everywhere possible.

This statement is really interesting but most incomprehensible. What do you mean with that. Can you explain it further? Thanks.

[Pinterest ](https://www.quora.com/What-challenges-has-Pinterest-encountered-with-Flask) and lots of other companys use Flask since years and they are happy. A nice [article ](https://medium.com/javascript-scene/the-shocking-secret-about-static-types-514d39bf30a3#.2dy5iddsv) about static and dynamic typing.

**Comment by philipithomas** [comment]
Realistically, weak typing didn't cause the errors, we did. We just didn't realize that we created bugs util runtime. That's one of the reasons we added the smoke testing framework - we had [80 endpoints](http://docs.staffjoy.com/) and were not doing a good job of unit testing due to the speed at which we were shipping features, so we basically wrote a test tool that hit every endpoint to make sure it wasn't erroring. 

Yes, others have run Flask successfully, and I love Flask and think that it is great. We just needed more "training wheels" to protect us from runtime errors.
