### ISSUE TITLE
is the project dead?

### ISSUE THREAD

**Issue by eddr** [Staffjoy/v2#11]
Hi

Should we expect any support?

Thanks!

**Comment by philipithomas** [comment]
Short answer, yes - it's dead. 

I open-sourced the code when we shut down the company. So, functionally the code was already unmaintained when it was published.

I help companies manage and deploy the code on a consulting basis. If you need help, please reach out (philip at moonlightwork.com). Many companies continue to run and modify the code, but it's forked to a closed branch.

Alas, the hard truth is that we shut down the Staffjoy company because it was unsuccessful. I hope that publishing the code helps some people, but I don't make any warranty that the product is amazing at this point, and I'm not spending my personal time improving something that has been unsuccessful.

**Comment by eddr** [comment]
Thanks! Much appreciated!
