### ISSUE TITLE
Question about microservice architecture

### ISSUE THREAD

**Issue by leandermelms** [Staffjoy/v2#6]
Hi, quick question: Why did you decide to let the company service manage shifts, jobs, admins, workers etc all together? Did you have plans to separate these into smaller units?

**Comment by philipithomas** [comment]
We separated `companies` and `accounts` separately based on permissions - the accounts system had no knowledge of companies, schedules, admins, etc.  We put all of the shifts, jobs, admins, etc under `companies` so that we could use SQL to do joins. 

We weren't planning on separating these into smaller units - we were planning on adding additional microservices that were integrations with other systems - e.g. FB messenger instead of texts, POS integrations, payroll integrations, etc
