### ISSUE TITLE
CI server

### ISSUE THREAD

**Issue by clanstyles** [Staffjoy/v2#7]
What CI server did you use when you ran Make build? How did your team trigger these and how long did it take with such a long complicated build?

**Comment by philipithomas** [comment]
We used self-hosted Jenkins. That way, lots of stuff is cached between builds with Bazel, Glide, and Yarn. We had three jobs - a "pull request tester" that ran tests against open pull requests from Github, a "build and stage" job that was triggered by changes to the `master` branch and ran tests, built all the services, and pushed the services to the staging environment. The third job allowed deploying an existing build to the production environment. 

Building all of the images and pushing them to the staging environment took less than 10 minutes on average. In fact, most of the builds came straight from the cache because Bazel had cached them during the "pull request tester" job we used. 

Promoting a build from staging to production took less than a minute - all it involves is telling the production kubernetes cluster to switch which images it uses. It's the same image used for staging, so it's already built and in the docker registry.
